name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: |
          uv run manage.py check
          uv run manage.py makemigrations
          uv run pytest --capture=no